/*
 * PatchFrame.java
 *
 * Created on 17. juni 2004, 13:24
 */

package no.machina.patcheditor.gui;

import java.util.*;
import javax.swing.event.*;
import no.machina.patcheditor.registry.*;

/**
 * 
 * @author  narve
 */
public class PatchFrame extends javax.swing.JFrame {
    
    /** Creates new form PatchFrame */
    public PatchFrame() {
        initComponents();
        setupTabbedPane();
    }
    

    private void setupTabbedPane() {
        ChangeListener changeListener = new ChangeListener() {
            public void stateChanged( ChangeEvent ce ) {
                PatchPanel pp = (PatchPanel)tabbedPane.getSelectedComponent();
                setJMenuBar( pp.getMBTop() );
            }
        };
        tabbedPane.getModel().addChangeListener( changeListener );
    }
    
    public void refreshTitles() {
        for( int i = 0; i < tabbedPane.getComponentCount(); i++ ) {
            PatchPanel pp = (PatchPanel)tabbedPane.getComponentAt( i );
            tabbedPane.setTitleAt( i, pp.getFileName() != null ? pp.getFileName() : "<empty>");
        }
    }
    
    public void newTab() {
        PatchPanel pp = new PatchPanel(); 
        tabbedPane.add( pp, "<empty>" ); 
        tabbedPane.setSelectedIndex( pp.getComponentCount()-1 ); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tabbedPane = new javax.swing.JTabbedPane();

        setTitle("Patch Editor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        close();
    }//GEN-LAST:event_exitForm
    
    
    public void close() {
        System.exit( 0 );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws Exception {
        javax.swing.UIManager.put("Menu.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
        javax.swing.UIManager.put("MenuItem.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
        javax.swing.UIManager.put("PopupMenu.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
        javax.swing.UIManager.put("RadioButtonMenuItem.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
        javax.swing.UIManager.put("TabbedPane.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
        javax.swing.UIManager.put("Label.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
        javax.swing.UIManager.put("TextField.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
        javax.swing.UIManager.put("Button.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
        javax.swing.UIManager.put("TitledBorder.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
        javax.swing.UIManager.put("Table.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,10));
        javax.swing.UIManager.put("TableHeader.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,10));
        javax.swing.UIManager.put("ComboBox.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,10));
        javax.swing.UIManager.put("CheckBox.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
        javax.swing.UIManager.put("List.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
        javax.swing.UIManager.put("TextArea.font",new java.awt.Font("Dialog",java.awt.Font.PLAIN,11));
       
        PatchPanel pg = new PatchPanel();
        
        PatchFrame jf = new PatchFrame();
        jf.tabbedPane.add( "<empty>", pg );
        
        if ( args.length >= 1 ) {
            System.out.println( "Opening " + args[ 0 ] );
            pg.fileOpen( args[ 0 ] );
        }
        jf.setSize( 1000, 800 );
        jf.setLocationRelativeTo( null );
        jf.setJMenuBar( pg.getMBTop() );
        jf.setVisible( true );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
    
}
